version: '3.8'

services:
  backend:
    build: .
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - D:\nodejs-crud\nodejs-crud\backend:/app
    container_name: node-server
    network:
      - backend-net
    


  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - daft_goods:/data/db
    network:
      - backend-net
    container_name: mongodb-server
